backend:
  name: git-gateway
  branch: master
media_folder: "imgs/uploads"
collections: 
  - name: "service-slide"
    label: "Service Slide"
    folder: "_posts/gallery-imgs/gallery-imgs.json"
    create: true
    slug: "gallery-{{slug}}"
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string"
      }
      - {
        label: "Image",
        name: "image",
        widget: "image"
      }
      - {
        label: "Alt Text",
        name: "altText",
        widget: "string"
      }